// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Firebase options for the web platform.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsOe7p6BITWcCYS3OLMqDnAV443MtjIzM',
    appId: '1:789328444858:web:22b6b93acd49ec6f923183',
    messagingSenderId: '789328444858',
    projectId: 'tomata-877aa',
    authDomain: 'tomata-877aa.firebaseapp.com',
    storageBucket: 'tomata-877aa.appspot.com',
  );

  /// Firebase options for the Android platform.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDcm0MCgodjL5f8GfkvzdEDF_iKJJcNvQ',
    appId: '1:789328444858:android:08285aed6eed084b923183',
    messagingSenderId: '789328444858',
    projectId: 'tomata-877aa',
    storageBucket: 'tomata-877aa.appspot.com',
  );

  /// Firebase options for the iOS platform.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0v-Ov8v1-8OD3IIgBhbf_H1NDFRKjMyY',
    appId: '1:789328444858:ios:42a120c5b0b833d2923183',
    messagingSenderId: '789328444858',
    projectId: 'tomata-877aa',
    storageBucket: 'tomata-877aa.appspot.com',
    iosBundleId: 'com.cis.tomato.tomato',
  );

  /// Firebase options for the macOS platform.
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0v-Ov8v1-8OD3IIgBhbf_H1NDFRKjMyY',
    appId: '1:789328444858:ios:229c915cd6c455ae923183',
    messagingSenderId: '789328444858',
    projectId: 'tomata-877aa',
    storageBucket: 'tomata-877aa.appspot.com',
    iosBundleId: 'com.cis.tomato.tomato.RunnerTests',
  );
}
